version: '3'
services:
  kurento-many2many:
    environment:
      - KURENTO_MEDIA_SERVER_HOST
      - KURENTO_MEDIA_SERVER_PORT
    build:
      context: ./kurento-many2many
    ports:
      - ${KURENTO_NODEJS_MANY2MANY_SERVER_PORT}:8443
  kurento-media-server:
    environment:
      - KMS_TURN_URL=${KMS_TURN_URL}
      - KMS_STUN_IP=${KMS_STUN_IP}
      - KMS_STUN_PORT=${KMS_STUN_PORT}
    image: "kurento/kurento-media-server:xenial-latest"
    ports:
      - ${KURENTO_MEDIA_SERVER_PORT}:8888
